using Microsoft.Maui.Controls.Shapes;

namespace MAUI.Demo.Components.UI;

// Stroke icons from ShellIcons (https://github.com/shellui-dev/shell-icons), derived from
// Lucide 0.475.0 (ISC license) — the icon set ShellUI uses. Drawn with MAUI shapes: no font or
// package, crisp at any size, theme-aware. Generated by scripts/generate-icons.py; a curated set
// of 110 icons — add names there and re-run to include more.
// Usage: <ui:Icon Name="Search" Size="16" />   Tint with Token="MutedForeground" or Color="Red".
public enum IconName
{
    None,
    Check,
    X,
    Plus,
    Minus,
    Search,
    Filter,
    Settings,
    SlidersHorizontal,
    Pencil,
    Trash,
    Trash2,
    Copy,
    Clipboard,
    Save,
    Download,
    Upload,
    Share,
    Share2,
    ExternalLink,
    Link,
    RefreshCw,
    RotateCcw,
    Undo2,
    Redo2,
    LogIn,
    LogOut,
    Send,
    Paperclip,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    ChevronsUpDown,
    ChevronsLeft,
    ChevronsRight,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    ArrowUpRight,
    Menu,
    Ellipsis,
    EllipsisVertical,
    GripVertical,
    House,
    LayoutDashboard,
    PanelLeft,
    Info,
    CircleAlert,
    CircleCheck,
    CircleX,
    CircleHelp,
    TriangleAlert,
    Ban,
    Loader,
    LoaderCircle,
    Bell,
    Circle,
    CirclePlus,
    Dot,
    User,
    Users,
    UserPlus,
    Lock,
    LockOpen,
    Key,
    Shield,
    Eye,
    EyeOff,
    Mail,
    Inbox,
    Archive,
    MessageCircle,
    Phone,
    Calendar,
    Clock,
    Globe,
    MapPin,
    Image,
    File,
    FileText,
    Folder,
    Tag,
    Bookmark,
    Heart,
    Star,
    ThumbsUp,
    ShoppingCart,
    CreditCard,
    DollarSign,
    Activity,
    TrendingUp,
    ChartColumn,
    Zap,
    Sparkles,
    Command,
    Terminal,
    Code,
    Moon,
    Sun,
    Monitor,
    Smartphone,
    Laptop,
    Wifi,
    Camera,
    Mic,
    Play,
    Pause,
    Volume2,
    Lightbulb
}

public static class IconPaths
{
    // Absolute path data on Lucide's 24x24 grid, drawn with a 2px round stroke.
    public static string Get(IconName name) => name switch
    {
        IconName.Check => "M 20 6 L 9 17 L 4 12",
        IconName.X => "M 18 6 L 6 18 M 6 6 L 18 18",
        IconName.Plus => "M 5 12 L 19 12 M 12 5 L 12 19",
        IconName.Minus => "M 5 12 L 19 12",
        IconName.Search => "M 19 11 A 8 8 0 1 1 3 11 A 8 8 0 1 1 19 11 Z M 21 21 L 16.7 16.7",
        IconName.Filter => "M 22 3 L 2 3 L 10 12.46 L 10 19 L 14 21 L 14 12.46 L 22 3 Z",
        IconName.Settings => "M 12.22 2 L 11.78 2 A 2 2 0 0 0 9.78 4 L 9.78 4.18 A 2 2 0 0 1 8.78 5.91 L 8.35 6.16 A 2 2 0 0 1 6.35 6.16 L 6.2 6.08 A 2 2 0 0 0 3.47 6.81 L 3.25 7.19 A 2 2 0 0 0 3.98 9.92 L 4.13 10.02 A 2 2 0 0 1 5.13 11.74 L 5.13 12.25 A 2 2 0 0 1 4.13 13.99 L 3.98 14.08 A 2 2 0 0 0 3.25 16.81 L 3.47 17.19 A 2 2 0 0 0 6.2 17.92 L 6.35 17.84 A 2 2 0 0 1 8.35 17.84 L 8.78 18.09 A 2 2 0 0 1 9.78 19.82 L 9.78 20 A 2 2 0 0 0 11.78 22 L 12.22 22 A 2 2 0 0 0 14.22 20 L 14.22 19.82 A 2 2 0 0 1 15.22 18.09 L 15.65 17.84 A 2 2 0 0 1 17.65 17.84 L 17.8 17.92 A 2 2 0 0 0 20.53 17.19 L 20.75 16.8 A 2 2 0 0 0 20.02 14.07 L 19.87 13.99 A 2 2 0 0 1 18.87 12.25 L 18.87 11.75 A 2 2 0 0 1 19.87 10.01 L 20.02 9.92 A 2 2 0 0 0 20.75 7.19 L 20.53 6.81 A 2 2 0 0 0 17.8 6.08 L 17.65 6.16 A 2 2 0 0 1 15.65 6.16 L 15.22 5.91 A 2 2 0 0 1 14.22 4.18 L 14.22 4 A 2 2 0 0 0 12.22 2 Z M 15 12 A 3 3 0 1 1 9 12 A 3 3 0 1 1 15 12 Z",
        IconName.SlidersHorizontal => "M 21 4 L 14 4 M 10 4 L 3 4 M 21 12 L 12 12 M 8 12 L 3 12 M 21 20 L 16 20 M 12 20 L 3 20 M 14 2 L 14 6 M 8 10 L 8 14 M 16 18 L 16 22",
        IconName.Pencil => "M 21.174 6.812 A 1 1 0 0 0 17.188 2.825 L 3.842 16.174 A 2 2 0 0 0 3.342 17.004 L 2.021 21.356 A 0.5 0.5 0 0 0 2.644 21.978 L 6.997 20.658 A 2 2 0 0 0 7.827 20.161 Z M 15 5 L 19 9",
        IconName.Trash => "M 3 6 L 21 6 M 19 6 L 19 20 C 19 21 18 22 17 22 L 7 22 C 6 22 5 21 5 20 L 5 6 M 8 6 L 8 4 C 8 3 9 2 10 2 L 14 2 C 15 2 16 3 16 4 L 16 6",
        IconName.Trash2 => "M 3 6 L 21 6 M 19 6 L 19 20 C 19 21 18 22 17 22 L 7 22 C 6 22 5 21 5 20 L 5 6 M 8 6 L 8 4 C 8 3 9 2 10 2 L 14 2 C 15 2 16 3 16 4 L 16 6 M 10 11 L 10 17 M 14 11 L 14 17",
        IconName.Copy => "M 10 8 L 20 8 A 2 2 0 0 1 22 10 L 22 20 A 2 2 0 0 1 20 22 L 10 22 A 2 2 0 0 1 8 20 L 8 10 A 2 2 0 0 1 10 8 Z M 4 16 C 2.9 16 2 15.1 2 14 L 2 4 C 2 2.9 2.9 2 4 2 L 14 2 C 15.1 2 16 2.9 16 4",
        IconName.Clipboard => "M 9 2 L 15 2 A 1 1 0 0 1 16 3 L 16 5 A 1 1 0 0 1 15 6 L 9 6 A 1 1 0 0 1 8 5 L 8 3 A 1 1 0 0 1 9 2 Z M 16 4 L 18 4 A 2 2 0 0 1 20 6 L 20 20 A 2 2 0 0 1 18 22 L 6 22 A 2 2 0 0 1 4 20 L 4 6 A 2 2 0 0 1 6 4 L 8 4",
        IconName.Save => "M 15.2 3 A 2 2 0 0 1 16.6 3.6 L 20.4 7.4 A 2 2 0 0 1 21 8.8 L 21 19 A 2 2 0 0 1 19 21 L 5 21 A 2 2 0 0 1 3 19 L 3 5 A 2 2 0 0 1 5 3 Z M 17 21 L 17 14 A 1 1 0 0 0 16 13 L 8 13 A 1 1 0 0 0 7 14 L 7 21 M 7 3 L 7 7 A 1 1 0 0 0 8 8 L 15 8",
        IconName.Download => "M 21 15 L 21 19 A 2 2 0 0 1 19 21 L 5 21 A 2 2 0 0 1 3 19 L 3 15 M 7 10 L 12 15 L 17 10 M 12 15 L 12 3",
        IconName.Upload => "M 21 15 L 21 19 A 2 2 0 0 1 19 21 L 5 21 A 2 2 0 0 1 3 19 L 3 15 M 17 8 L 12 3 L 7 8 M 12 3 L 12 15",
        IconName.Share => "M 4 12 L 4 20 A 2 2 0 0 0 6 22 L 18 22 A 2 2 0 0 0 20 20 L 20 12 M 16 6 L 12 2 L 8 6 M 12 2 L 12 15",
        IconName.Share2 => "M 21 5 A 3 3 0 1 1 15 5 A 3 3 0 1 1 21 5 Z M 9 12 A 3 3 0 1 1 3 12 A 3 3 0 1 1 9 12 Z M 21 19 A 3 3 0 1 1 15 19 A 3 3 0 1 1 21 19 Z M 8.59 13.51 L 15.42 17.49 M 15.41 6.51 L 8.59 10.49",
        IconName.ExternalLink => "M 15 3 L 21 3 L 21 9 M 10 14 L 21 3 M 18 13 L 18 19 A 2 2 0 0 1 16 21 L 5 21 A 2 2 0 0 1 3 19 L 3 8 A 2 2 0 0 1 5 6 L 11 6",
        IconName.Link => "M 10 13 A 5 5 0 0 0 17.54 13.54 L 20.54 10.54 A 5 5 0 0 0 13.47 3.47 L 11.75 5.18 M 14 11 A 5 5 0 0 0 6.46 10.46 L 3.46 13.46 A 5 5 0 0 0 10.53 20.53 L 12.24 18.82",
        IconName.RefreshCw => "M 3 12 A 9 9 0 0 1 12 3 A 9.75 9.75 0 0 1 18.74 5.74 L 21 8 M 21 3 L 21 8 L 16 8 M 21 12 A 9 9 0 0 1 12 21 A 9.75 9.75 0 0 1 5.26 18.26 L 3 16 M 8 16 L 3 16 L 3 21",
        IconName.RotateCcw => "M 3 12 A 9 9 0 1 0 12 3 A 9.75 9.75 0 0 0 5.26 5.74 L 3 8 M 3 3 L 3 8 L 8 8",
        IconName.Undo2 => "M 9 14 L 4 9 L 9 4 M 4 9 L 14.5 9 A 5.5 5.5 0 0 1 20 14.5 A 5.5 5.5 0 0 1 14.5 20 L 11 20",
        IconName.Redo2 => "M 15 14 L 20 9 L 15 4 M 20 9 L 9.5 9 A 5.5 5.5 0 0 0 4 14.5 A 5.5 5.5 0 0 0 9.5 20 L 13 20",
        IconName.LogIn => "M 15 3 L 19 3 A 2 2 0 0 1 21 5 L 21 19 A 2 2 0 0 1 19 21 L 15 21 M 10 17 L 15 12 L 10 7 M 15 12 L 3 12",
        IconName.LogOut => "M 9 21 L 5 21 A 2 2 0 0 1 3 19 L 3 5 A 2 2 0 0 1 5 3 L 9 3 M 16 17 L 21 12 L 16 7 M 21 12 L 9 12",
        IconName.Send => "M 14.536 21.686 A 0.5 0.5 0 0 0 15.473 21.662 L 21.973 2.662 A 0.496 0.496 0 0 0 21.338 2.027 L 2.338 8.527 A 0.5 0.5 0 0 0 2.314 9.464 L 10.244 12.644 A 2 2 0 0 1 11.356 13.754 Z M 21.854 2.147 L 10.914 13.086",
        IconName.Paperclip => "M 13.234 20.252 L 21 12.3 M 16 6 L 7.586 14.586 A 2 2 0 0 0 7.586 17.414 A 2 2 0 0 0 10.414 17.414 L 18.828 8.828 A 4 4 0 0 0 18.828 3.172 A 4 4 0 0 0 13.172 3.172 L 4.757 11.757 A 6 6 0 1 0 13.243 20.243",
        IconName.ChevronDown => "M 6 9 L 12 15 L 18 9",
        IconName.ChevronUp => "M 18 15 L 12 9 L 6 15",
        IconName.ChevronLeft => "M 15 18 L 9 12 L 15 6",
        IconName.ChevronRight => "M 9 18 L 15 12 L 9 6",
        IconName.ChevronsUpDown => "M 7 15 L 12 20 L 17 15 M 7 9 L 12 4 L 17 9",
        IconName.ChevronsLeft => "M 11 17 L 6 12 L 11 7 M 18 17 L 13 12 L 18 7",
        IconName.ChevronsRight => "M 6 17 L 11 12 L 6 7 M 13 17 L 18 12 L 13 7",
        IconName.ArrowLeft => "M 12 19 L 5 12 L 12 5 M 19 12 L 5 12",
        IconName.ArrowRight => "M 5 12 L 19 12 M 12 5 L 19 12 L 12 19",
        IconName.ArrowUp => "M 5 12 L 12 5 L 19 12 M 12 19 L 12 5",
        IconName.ArrowDown => "M 12 5 L 12 19 M 19 12 L 12 19 L 5 12",
        IconName.ArrowUpRight => "M 7 7 L 17 7 L 17 17 M 7 17 L 17 7",
        IconName.Menu => "M 4 12 L 20 12 M 4 6 L 20 6 M 4 18 L 20 18",
        IconName.Ellipsis => "M 13 12 A 1 1 0 1 1 11 12 A 1 1 0 1 1 13 12 Z M 20 12 A 1 1 0 1 1 18 12 A 1 1 0 1 1 20 12 Z M 6 12 A 1 1 0 1 1 4 12 A 1 1 0 1 1 6 12 Z",
        IconName.EllipsisVertical => "M 13 12 A 1 1 0 1 1 11 12 A 1 1 0 1 1 13 12 Z M 13 5 A 1 1 0 1 1 11 5 A 1 1 0 1 1 13 5 Z M 13 19 A 1 1 0 1 1 11 19 A 1 1 0 1 1 13 19 Z",
        IconName.GripVertical => "M 10 12 A 1 1 0 1 1 8 12 A 1 1 0 1 1 10 12 Z M 10 5 A 1 1 0 1 1 8 5 A 1 1 0 1 1 10 5 Z M 10 19 A 1 1 0 1 1 8 19 A 1 1 0 1 1 10 19 Z M 16 12 A 1 1 0 1 1 14 12 A 1 1 0 1 1 16 12 Z M 16 5 A 1 1 0 1 1 14 5 A 1 1 0 1 1 16 5 Z M 16 19 A 1 1 0 1 1 14 19 A 1 1 0 1 1 16 19 Z",
        IconName.House => "M 15 21 L 15 13 A 1 1 0 0 0 14 12 L 10 12 A 1 1 0 0 0 9 13 L 9 21 M 3 10 A 2 2 0 0 1 3.709 8.472 L 10.709 2.473 A 2 2 0 0 1 13.291 2.473 L 20.291 8.472 A 2 2 0 0 1 21 10 L 21 19 A 2 2 0 0 1 19 21 L 5 21 A 2 2 0 0 1 3 19 Z",
        IconName.LayoutDashboard => "M 4 3 L 9 3 A 1 1 0 0 1 10 4 L 10 11 A 1 1 0 0 1 9 12 L 4 12 A 1 1 0 0 1 3 11 L 3 4 A 1 1 0 0 1 4 3 Z M 15 3 L 20 3 A 1 1 0 0 1 21 4 L 21 7 A 1 1 0 0 1 20 8 L 15 8 A 1 1 0 0 1 14 7 L 14 4 A 1 1 0 0 1 15 3 Z M 15 12 L 20 12 A 1 1 0 0 1 21 13 L 21 20 A 1 1 0 0 1 20 21 L 15 21 A 1 1 0 0 1 14 20 L 14 13 A 1 1 0 0 1 15 12 Z M 4 16 L 9 16 A 1 1 0 0 1 10 17 L 10 20 A 1 1 0 0 1 9 21 L 4 21 A 1 1 0 0 1 3 20 L 3 17 A 1 1 0 0 1 4 16 Z",
        IconName.PanelLeft => "M 5 3 L 19 3 A 2 2 0 0 1 21 5 L 21 19 A 2 2 0 0 1 19 21 L 5 21 A 2 2 0 0 1 3 19 L 3 5 A 2 2 0 0 1 5 3 Z M 9 3 L 9 21",
        IconName.Info => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 12 16 L 12 12 M 12 8 L 12.01 8",
        IconName.CircleAlert => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 12 8 L 12 12 M 12 16 L 12.01 16",
        IconName.CircleCheck => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 9 12 L 11 14 L 15 10",
        IconName.CircleX => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 15 9 L 9 15 M 9 9 L 15 15",
        IconName.CircleHelp => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 9.09 9 A 3 3 0 0 1 14.92 10 C 14.92 12 11.92 13 11.92 13 M 12 17 L 12.01 17",
        IconName.TriangleAlert => "M 21.73 18 L 13.73 4 A 2 2 0 0 0 10.25 4 L 2.25 18 A 2 2 0 0 0 4 21 L 20 21 A 2 2 0 0 0 21.73 18 M 12 9 L 12 13 M 12 17 L 12.01 17",
        IconName.Ban => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 4.9 4.9 L 19.1 19.1",
        IconName.Loader => "M 12 2 L 12 6 M 16.2 7.8 L 19.1 4.9 M 18 12 L 22 12 M 16.2 16.2 L 19.1 19.1 M 12 18 L 12 22 M 4.9 19.1 L 7.8 16.2 M 2 12 L 6 12 M 4.9 4.9 L 7.8 7.8",
        IconName.LoaderCircle => "M 21 12 A 9 9 0 1 1 14.781 3.44",
        IconName.Bell => "M 10.268 21 A 2 2 0 0 0 13.732 21 M 3.262 15.326 A 1 1 0 0 0 4 17 L 20 17 A 1 1 0 0 0 20.74 15.327 C 19.41 13.956 18 12.499 18 8 A 6 6 0 0 0 6 8 C 6 12.499 4.589 13.956 3.262 15.326",
        IconName.Circle => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z",
        IconName.CirclePlus => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 8 12 L 16 12 M 12 8 L 12 16",
        IconName.Dot => "M 13.1 12.1 A 1 1 0 1 1 11.1 12.1 A 1 1 0 1 1 13.1 12.1 Z",
        IconName.User => "M 19 21 L 19 19 A 4 4 0 0 0 15 15 L 9 15 A 4 4 0 0 0 5 19 L 5 21 M 16 7 A 4 4 0 1 1 8 7 A 4 4 0 1 1 16 7 Z",
        IconName.Users => "M 16 21 L 16 19 A 4 4 0 0 0 12 15 L 6 15 A 4 4 0 0 0 2 19 L 2 21 M 13 7 A 4 4 0 1 1 5 7 A 4 4 0 1 1 13 7 Z M 22 21 L 22 19 A 4 4 0 0 0 19 15.13 M 16 3.13 A 4 4 0 0 1 16 10.88",
        IconName.UserPlus => "M 16 21 L 16 19 A 4 4 0 0 0 12 15 L 6 15 A 4 4 0 0 0 2 19 L 2 21 M 13 7 A 4 4 0 1 1 5 7 A 4 4 0 1 1 13 7 Z M 19 8 L 19 14 M 22 11 L 16 11",
        IconName.Lock => "M 5 11 L 19 11 A 2 2 0 0 1 21 13 L 21 20 A 2 2 0 0 1 19 22 L 5 22 A 2 2 0 0 1 3 20 L 3 13 A 2 2 0 0 1 5 11 Z M 7 11 L 7 7 A 5 5 0 0 1 17 7 L 17 11",
        IconName.LockOpen => "M 5 11 L 19 11 A 2 2 0 0 1 21 13 L 21 20 A 2 2 0 0 1 19 22 L 5 22 A 2 2 0 0 1 3 20 L 3 13 A 2 2 0 0 1 5 11 Z M 7 11 L 7 7 A 5 5 0 0 1 16.9 6",
        IconName.Key => "M 15.5 7.5 L 17.8 9.8 A 1 1 0 0 0 19.2 9.8 L 21.3 7.7 A 1 1 0 0 0 21.3 6.3 L 19 4 M 21 2 L 11.4 11.6 M 13 15.5 A 5.5 5.5 0 1 1 2 15.5 A 5.5 5.5 0 1 1 13 15.5 Z",
        IconName.Shield => "M 20 13 C 20 18 16.5 20.5 12.34 21.95 A 1 1 0 0 1 11.67 21.94 C 7.5 20.5 4 18 4 13 L 4 6 A 1 1 0 0 1 5 5 C 7 5 9.5 3.8 11.24 2.28 A 1.17 1.17 0 0 1 12.76 2.28 C 14.51 3.81 17 5 19 5 A 1 1 0 0 1 20 6 Z",
        IconName.Eye => "M 2.062 12.348 A 1 1 0 0 1 2.062 11.652 A 10.75 10.75 0 0 1 21.938 11.652 A 1 1 0 0 1 21.938 12.348 A 10.75 10.75 0 0 1 2.062 12.348 M 15 12 A 3 3 0 1 1 9 12 A 3 3 0 1 1 15 12 Z",
        IconName.EyeOff => "M 10.733 5.076 A 10.744 10.744 0 0 1 21.938 11.651 A 1 1 0 0 1 21.938 12.347 A 10.747 10.747 0 0 1 20.494 14.837 M 14.084 14.158 A 3 3 0 0 1 9.842 9.916 M 17.479 17.499 A 10.75 10.75 0 0 1 2.062 12.348 A 1 1 0 0 1 2.062 11.652 A 10.75 10.75 0 0 1 6.508 6.509 M 2 2 L 22 22",
        IconName.Mail => "M 4 4 L 20 4 A 2 2 0 0 1 22 6 L 22 18 A 2 2 0 0 1 20 20 L 4 20 A 2 2 0 0 1 2 18 L 2 6 A 2 2 0 0 1 4 4 Z M 22 7 L 13.03 12.7 A 1.94 1.94 0 0 1 10.97 12.7 L 2 7",
        IconName.Inbox => "M 22 12 L 16 12 L 14 15 L 10 15 L 8 12 L 2 12 M 5.45 5.11 L 2 12 L 2 18 A 2 2 0 0 0 4 20 L 20 20 A 2 2 0 0 0 22 18 L 22 12 L 18.55 5.11 A 2 2 0 0 0 16.76 4 L 7.24 4 A 2 2 0 0 0 5.45 5.11 Z",
        IconName.Archive => "M 3 3 L 21 3 A 1 1 0 0 1 22 4 L 22 7 A 1 1 0 0 1 21 8 L 3 8 A 1 1 0 0 1 2 7 L 2 4 A 1 1 0 0 1 3 3 Z M 4 8 L 4 19 A 2 2 0 0 0 6 21 L 18 21 A 2 2 0 0 0 20 19 L 20 8 M 10 12 L 14 12",
        IconName.MessageCircle => "M 7.9 20 A 9 9 0 1 0 4 16.1 L 2 22 Z",
        IconName.Phone => "M 22 16.92 L 22 19.92 A 2 2 0 0 1 19.82 21.92 A 19.79 19.79 0 0 1 11.19 18.85 A 19.5 19.5 0 0 1 5.19 12.85 A 19.79 19.79 0 0 1 2.12 4.18 A 2 2 0 0 1 4.11 2 L 7.11 2 A 2 2 0 0 1 9.11 3.72 A 12.84 12.84 0 0 0 9.81 6.53 A 2 2 0 0 1 9.36 8.64 L 8.09 9.91 A 16 16 0 0 0 14.09 15.91 L 15.36 14.64 A 2 2 0 0 1 17.47 14.19 A 12.84 12.84 0 0 0 20.28 14.89 A 2 2 0 0 1 22 16.92 Z",
        IconName.Calendar => "M 8 2 L 8 6 M 16 2 L 16 6 M 5 4 L 19 4 A 2 2 0 0 1 21 6 L 21 20 A 2 2 0 0 1 19 22 L 5 22 A 2 2 0 0 1 3 20 L 3 6 A 2 2 0 0 1 5 4 Z M 3 10 L 21 10",
        IconName.Clock => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 12 6 L 12 12 L 16 14",
        IconName.Globe => "M 22 12 A 10 10 0 1 1 2 12 A 10 10 0 1 1 22 12 Z M 12 2 A 14.5 14.5 0 0 0 12 22 A 14.5 14.5 0 0 0 12 2 M 2 12 L 22 12",
        IconName.MapPin => "M 20 10 C 20 14.993 14.461 20.193 12.601 21.799 A 1 1 0 0 1 11.399 21.799 C 9.539 20.193 4 14.993 4 10 A 8 8 0 0 1 20 10 M 15 10 A 3 3 0 1 1 9 10 A 3 3 0 1 1 15 10 Z",
        IconName.Image => "M 5 3 L 19 3 A 2 2 0 0 1 21 5 L 21 19 A 2 2 0 0 1 19 21 L 5 21 A 2 2 0 0 1 3 19 L 3 5 A 2 2 0 0 1 5 3 Z M 11 9 A 2 2 0 1 1 7 9 A 2 2 0 1 1 11 9 Z M 21 15 L 17.914 11.914 A 2 2 0 0 0 15.086 11.914 L 6 21",
        IconName.File => "M 15 2 L 6 2 A 2 2 0 0 0 4 4 L 4 20 A 2 2 0 0 0 6 22 L 18 22 A 2 2 0 0 0 20 20 L 20 7 Z M 14 2 L 14 6 A 2 2 0 0 0 16 8 L 20 8",
        IconName.FileText => "M 15 2 L 6 2 A 2 2 0 0 0 4 4 L 4 20 A 2 2 0 0 0 6 22 L 18 22 A 2 2 0 0 0 20 20 L 20 7 Z M 14 2 L 14 6 A 2 2 0 0 0 16 8 L 20 8 M 10 9 L 8 9 M 16 13 L 8 13 M 16 17 L 8 17",
        IconName.Folder => "M 20 20 A 2 2 0 0 0 22 18 L 22 8 A 2 2 0 0 0 20 6 L 12.1 6 A 2 2 0 0 1 10.41 5.1 L 9.6 3.9 A 2 2 0 0 0 7.93 3 L 4 3 A 2 2 0 0 0 2 5 L 2 18 A 2 2 0 0 0 4 20 Z",
        IconName.Tag => "M 12.586 2.586 A 2 2 0 0 0 11.172 2 L 4 2 A 2 2 0 0 0 2 4 L 2 11.172 A 2 2 0 0 0 2.586 12.586 L 11.29 21.29 A 2.426 2.426 0 0 0 14.71 21.29 L 21.29 14.71 A 2.426 2.426 0 0 0 21.29 11.29 Z M 8 7.5 A 0.5 0.5 0 1 1 7 7.5 A 0.5 0.5 0 1 1 8 7.5 Z",
        IconName.Bookmark => "M 19 21 L 12 17 L 5 21 L 5 5 A 2 2 0 0 1 7 3 L 17 3 A 2 2 0 0 1 19 5 L 19 21 Z",
        IconName.Heart => "M 19 14 C 20.49 12.54 22 10.79 22 8.5 A 5.5 5.5 0 0 0 16.5 3 C 14.74 3 13.5 3.5 12 5 C 10.5 3.5 9.26 3 7.5 3 A 5.5 5.5 0 0 0 2 8.5 C 2 10.8 3.5 12.55 5 14 L 12 21 Z",
        IconName.Star => "M 11.525 2.295 A 0.53 0.53 0 0 1 12.475 2.295 L 14.785 6.974 A 2.123 2.123 0 0 0 16.38 8.134 L 21.546 8.89 A 0.53 0.53 0 0 1 21.84 9.794 L 18.104 13.432 A 2.123 2.123 0 0 0 17.493 15.31 L 18.375 20.45 A 0.53 0.53 0 0 1 17.604 21.01 L 12.986 18.582 A 2.122 2.122 0 0 0 11.013 18.582 L 6.396 21.01 A 0.53 0.53 0 0 1 5.626 20.45 L 6.507 15.311 A 2.122 2.122 0 0 0 5.896 13.432 L 2.16 9.795 A 0.53 0.53 0 0 1 2.454 8.889 L 7.619 8.134 A 2.122 2.122 0 0 0 9.216 6.974 Z",
        IconName.ThumbsUp => "M 7 10 L 7 22 M 15 5.88 L 14 10 L 19.83 10 A 2 2 0 0 1 21.75 12.56 L 19.42 20.56 A 2 2 0 0 1 17.5 22 L 4 22 A 2 2 0 0 1 2 20 L 2 12 A 2 2 0 0 1 4 10 L 6.76 10 A 2 2 0 0 0 8.55 8.89 L 12 2 A 3.13 3.13 0 0 1 15 5.88 Z",
        IconName.ShoppingCart => "M 9 21 A 1 1 0 1 1 7 21 A 1 1 0 1 1 9 21 Z M 20 21 A 1 1 0 1 1 18 21 A 1 1 0 1 1 20 21 Z M 2.05 2.05 L 4.05 2.05 L 6.71 14.47 A 2 2 0 0 0 8.71 16.05 L 18.49 16.05 A 2 2 0 0 0 20.44 14.48 L 22.09 7.05 L 5.12 7.05",
        IconName.CreditCard => "M 4 5 L 20 5 A 2 2 0 0 1 22 7 L 22 17 A 2 2 0 0 1 20 19 L 4 19 A 2 2 0 0 1 2 17 L 2 7 A 2 2 0 0 1 4 5 Z M 2 10 L 22 10",
        IconName.DollarSign => "M 12 2 L 12 22 M 17 5 L 9.5 5 A 3.5 3.5 0 0 0 9.5 12 L 14.5 12 A 3.5 3.5 0 0 1 14.5 19 L 6 19",
        IconName.Activity => "M 22 12 L 19.52 12 A 2 2 0 0 0 17.59 13.46 L 15.24 21.82 A 0.25 0.25 0 0 1 14.76 21.82 L 9.24 2.18 A 0.25 0.25 0 0 0 8.76 2.18 L 6.41 10.54 A 2 2 0 0 1 4.49 12 L 2 12",
        IconName.TrendingUp => "M 22 7 L 13.5 15.5 L 8.5 10.5 L 2 17 M 16 7 L 22 7 L 22 13",
        IconName.ChartColumn => "M 3 3 L 3 19 A 2 2 0 0 0 5 21 L 21 21 M 18 17 L 18 9 M 13 17 L 13 5 M 8 17 L 8 14",
        IconName.Zap => "M 4 14 A 1 1 0 0 1 3.22 12.37 L 13.12 2.17 A 0.5 0.5 0 0 1 13.98 2.63 L 12.06 8.65 A 1 1 0 0 0 13 10 L 20 10 A 1 1 0 0 1 20.78 11.63 L 10.88 21.83 A 0.5 0.5 0 0 1 10.02 21.37 L 11.94 15.35 A 1 1 0 0 0 11 14 Z",
        IconName.Sparkles => "M 9.937 15.5 A 2 2 0 0 0 8.5 14.063 L 2.365 12.481 A 0.5 0.5 0 0 1 2.365 11.519 L 8.5 9.936 A 2 2 0 0 0 9.937 8.5 L 11.519 2.365 A 0.5 0.5 0 0 1 12.482 2.365 L 14.063 8.5 A 2 2 0 0 0 15.5 9.937 L 21.635 11.518 A 0.5 0.5 0 0 1 21.635 12.482 L 15.5 14.063 A 2 2 0 0 0 14.063 15.5 L 12.481 21.635 A 0.5 0.5 0 0 1 11.518 21.635 Z M 20 3 L 20 7 M 22 5 L 18 5 M 4 17 L 4 19 M 5 18 L 3 18",
        IconName.Command => "M 15 6 L 15 18 A 3 3 0 1 0 18 15 L 6 15 A 3 3 0 1 0 9 18 L 9 6 A 3 3 0 1 0 6 9 L 18 9 A 3 3 0 1 0 15 6",
        IconName.Terminal => "M 4 17 L 10 11 L 4 5 M 12 19 L 20 19",
        IconName.Code => "M 16 18 L 22 12 L 16 6 M 8 6 L 2 12 L 8 18",
        IconName.Moon => "M 12 3 A 6 6 0 0 0 21 12 A 9 9 0 1 1 12 3 Z",
        IconName.Sun => "M 16 12 A 4 4 0 1 1 8 12 A 4 4 0 1 1 16 12 Z M 12 2 L 12 4 M 12 20 L 12 22 M 4.93 4.93 L 6.34 6.34 M 17.66 17.66 L 19.07 19.07 M 2 12 L 4 12 M 20 12 L 22 12 M 6.34 17.66 L 4.93 19.07 M 19.07 4.93 L 17.66 6.34",
        IconName.Monitor => "M 4 3 L 20 3 A 2 2 0 0 1 22 5 L 22 15 A 2 2 0 0 1 20 17 L 4 17 A 2 2 0 0 1 2 15 L 2 5 A 2 2 0 0 1 4 3 Z M 8 21 L 16 21 M 12 17 L 12 21",
        IconName.Smartphone => "M 7 2 L 17 2 A 2 2 0 0 1 19 4 L 19 20 A 2 2 0 0 1 17 22 L 7 22 A 2 2 0 0 1 5 20 L 5 4 A 2 2 0 0 1 7 2 Z M 12 18 L 12.01 18",
        IconName.Laptop => "M 20 16 L 20 7 A 2 2 0 0 0 18 5 L 6 5 A 2 2 0 0 0 4 7 L 4 16 M 20 16 L 4 16 M 20 16 L 21.28 18.55 A 1 1 0 0 1 20.38 20 L 3.62 20 A 1 1 0 0 1 2.72 18.55 L 4 16",
        IconName.Wifi => "M 12 20 L 12.01 20 M 2 8.82 A 15 15 0 0 1 22 8.82 M 5 12.859 A 10 10 0 0 1 19 12.859 M 8.5 16.429 A 5 5 0 0 1 15.5 16.429",
        IconName.Camera => "M 14.5 4 L 9.5 4 L 7 7 L 4 7 A 2 2 0 0 0 2 9 L 2 18 A 2 2 0 0 0 4 20 L 20 20 A 2 2 0 0 0 22 18 L 22 9 A 2 2 0 0 0 20 7 L 17 7 L 14.5 4 Z M 15 13 A 3 3 0 1 1 9 13 A 3 3 0 1 1 15 13 Z",
        IconName.Mic => "M 12 2 A 3 3 0 0 0 9 5 L 9 12 A 3 3 0 0 0 15 12 L 15 5 A 3 3 0 0 0 12 2 Z M 19 10 L 19 12 A 7 7 0 0 1 5 12 L 5 10 M 12 19 L 12 22",
        IconName.Play => "M 6 3 L 20 12 L 6 21 L 6 3 Z",
        IconName.Pause => "M 15 4 L 17 4 A 1 1 0 0 1 18 5 L 18 19 A 1 1 0 0 1 17 20 L 15 20 A 1 1 0 0 1 14 19 L 14 5 A 1 1 0 0 1 15 4 Z M 7 4 L 9 4 A 1 1 0 0 1 10 5 L 10 19 A 1 1 0 0 1 9 20 L 7 20 A 1 1 0 0 1 6 19 L 6 5 A 1 1 0 0 1 7 4 Z",
        IconName.Volume2 => "M 11 4.702 A 0.705 0.705 0 0 0 9.797 4.204 L 6.413 7.587 A 1.4 1.4 0 0 1 5.416 8 L 3 8 A 1 1 0 0 0 2 9 L 2 15 A 1 1 0 0 0 3 16 L 5.416 16 A 1.4 1.4 0 0 1 6.413 16.413 L 9.796 19.797 A 0.705 0.705 0 0 0 11 19.298 Z M 16 9 A 5 5 0 0 1 16 15 M 19.364 18.364 A 9 9 0 0 0 19.364 5.636",
        IconName.Lightbulb => "M 15 14 C 15.2 13 15.7 12.3 16.5 11.5 C 17.5 10.6 18 9.3 18 8 A 6 6 0 0 0 6 8 C 6 9 6.2 10.2 7.5 11.5 C 8.2 12.2 8.8 13 9 14 M 9 18 L 15 18 M 10 22 L 14 22",
        _ => string.Empty
    };
}

public partial class Icon : ContentView
{
    public static readonly BindableProperty NameProperty =
        BindableProperty.Create(nameof(Name), typeof(IconName), typeof(Icon), IconName.None,
            propertyChanged: (b, o, n) => (b as Icon)?.UpdateGeometry());

    public static readonly BindableProperty SizeProperty =
        BindableProperty.Create(nameof(Size), typeof(double), typeof(Icon), 16.0,
            propertyChanged: (b, o, n) => (b as Icon)?.UpdateGeometry());

    public static readonly BindableProperty StrokeWidthProperty =
        BindableProperty.Create(nameof(StrokeWidth), typeof(double), typeof(Icon), 2.0,
            propertyChanged: (b, o, n) => (b as Icon)?.UpdateGeometry());

    public static readonly BindableProperty TokenProperty =
        BindableProperty.Create(nameof(Token), typeof(ShellToken), typeof(Icon), ShellToken.Foreground,
            propertyChanged: (b, o, n) => (b as Icon)?.UpdateColor());

    // Explicit color; overrides Token when set.
    public static readonly BindableProperty ColorProperty =
        BindableProperty.Create(nameof(Color), typeof(Color), typeof(Icon), null,
            propertyChanged: (b, o, n) => (b as Icon)?.UpdateColor());

    public IconName Name
    {
        get => (IconName)GetValue(NameProperty);
        set => SetValue(NameProperty, value);
    }

    public double Size
    {
        get => (double)GetValue(SizeProperty);
        set => SetValue(SizeProperty, value);
    }

    public double StrokeWidth
    {
        get => (double)GetValue(StrokeWidthProperty);
        set => SetValue(StrokeWidthProperty, value);
    }

    public ShellToken Token
    {
        get => (ShellToken)GetValue(TokenProperty);
        set => SetValue(TokenProperty, value);
    }

    public Color? Color
    {
        get => (Color?)GetValue(ColorProperty);
        set => SetValue(ColorProperty, value);
    }

    private readonly Microsoft.Maui.Controls.Shapes.Path _path;

    public Icon()
    {
        _path = new Microsoft.Maui.Controls.Shapes.Path
        {
            Aspect = Stretch.None,
            StrokeLineCap = PenLineCap.Round,
            StrokeLineJoin = PenLineJoin.Round,
            HorizontalOptions = LayoutOptions.Start,
            VerticalOptions = LayoutOptions.Start
        };
        Content = _path;
        HorizontalOptions = LayoutOptions.Center;
        VerticalOptions = LayoutOptions.Center;
        InputTransparent = true;
        UpdateGeometry();
        UpdateColor();
    }

    private void UpdateGeometry()
    {
        var data = IconPaths.Get(Name);
        _path.Data = string.IsNullOrEmpty(data)
            ? null
            : (Geometry?)new PathGeometryConverter().ConvertFromInvariantString(data);
        // Scale the 24x24 grid to Size; the stroke scales with it so icons keep Lucide's weight.
        var scale = Size / 24.0;
        _path.RenderTransform = new ScaleTransform(scale, scale);
        _path.StrokeThickness = StrokeWidth * scale;
        _path.WidthRequest = Size;
        _path.HeightRequest = Size;
        WidthRequest = Size;
        HeightRequest = Size;
    }

    private void UpdateColor()
    {
        if (Color != null)
        {
            _path.Stroke = new SolidColorBrush(Color);
        }
        else
        {
            _path.ClearValue(Microsoft.Maui.Controls.Shapes.Shape.StrokeProperty);
            _path.Token(Microsoft.Maui.Controls.Shapes.Shape.StrokeProperty, Token);
        }
    }
}
